### ISSUE TITLE
Alarms created by this CDK stack not displayed in generated Dashboard

### ISSUE THREAD

**Issue by pchaganti** [aws-samples/tag-based-cloudwatch-dashboard#10]
When we do cdk deploy, it creates several alarms in the stack. For instance it creates several DynamoDB alarms for my table which is found when we do getResources.sh. But these created alarms are not shown on the generated dashboard. I see a space at the top which is titled Alarms but is empty. 

Is there a configuration step I am missing?

thanks!

![Screen Shot 2022-03-09 at 12 37 54 PM](https://user-images.githubusercontent.com/6500/157499213-6b610542-01a5-492c-bef3-9575cd0137b2.jpg)

**Comment by zzorp** [comment]
Thanks for the report! I will look into this as soon as possible.

Meanwhile, did you try resizing (increasing hight) the alarm widget, just to see if they are hidden? Did you see the alarms being generated on "All alarms"-page?

**Comment by pchaganti** [comment]
The alarms are displayed in the All alarms page. I resized the widget but it is empty.

thanks!

**Comment by zzorp** [comment]
Ah of course they are. They are created prior to the widget building step. Let me work on this. I might have a solution tomorrow or at least on Monday.

**Comment by zzorp** [comment]
Hi again, I'm having difficulties to reproduce it, aka "it shouldn't be happening". :) 

Could you please submit output of `git log -n 1` here. 
Then try to destroy the dashboard with `cdk destroy` and do a clean deploy with `cdk deploy`. 

Then if the "git command" doesn't show `commit 6c76e0d957d954b10e153e5ce9b1574b8f08dd06` do a git pull to get the latest and retry destroy and deploy.

If neither works, I'm open for arranging a screen-share or something to help troubleshoot.

**Comment by pchaganti** [comment]
Will destroy and recreate the dashboard. Update you once I try out these things.

thanks

**Comment by pchaganti** [comment]
I destroyed and recreated the dashboard after pulling latest source. Confirm that it does work. I can see the alarms displayed on the dashboard.

Thank you for taking a look at this!

**Comment by zzorp** [comment]
Thank YOU for reporting! It helps me make it better. Glad that it's working now. Keep the reports coming if you run into more trouble.
