### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by pchaganti** [aws-samples/tag-based-cloudwatch-dashboard#7]
Deployment ends up with this error. The AWS account has mostly Lambda, Aurora serverless and ECS resources. Any idea what could be causing this?

```
IemDashboardStack: deploying...
[0%] start: Publishing d6d4f3b9a4d43573e657059eb71cca92c8bc113e612c9f4e97ccf66b9dcbbc4b:current_account-current_region
[100%] success: Published d6d4f3b9a4d43573e657059eb71cca92c8bc113e612c9f4e97ccf66b9dcbbc4b:current_account-current_region
IemDashboardStack: creating CloudFormation changeset...
8:06:57 AM | CREATE_FAILED        | AWS::CloudWatch::Dashboard | MyTestB3FF2C3A
The dashboard body is invalid, there are 1 validation errors:
[
{
"dataPath": "/widgets/0/properties/alarms",
"message": "Should NOT have less than 1 items"
}
] (Service: AmazonCloudWatch; Status Code: 400; Error Code: InvalidParameterInput; Request ID: 432d8488-fbe0-4038-99b7-634d5cc1b446; Proxy: null)

```

**Comment by zzorp** [comment]
Thanks for the report. I will look into it ASAP. I will follow up with questions if necessary.

**Comment by zzorp** [comment]
This is now fixed. Pull, and let me know if it works better. Let me know if you find other problems. I haven't tested Aurora serverless yet, so let me know if you miss anything there.

**Comment by pchaganti** [comment]
Tried it with another account that also has ECS and Lambda. Worked just fine.

Will also try it with the account that uses serverless aurora.

Thanks for the quick fix!

**Comment by pchaganti** [comment]
Works just fine with Aurora serverless too!

**Comment by zzorp** [comment]
Fantastic! Thanks!
